<a href="https://colab.research.google.com/github/Rstam59/TaskDataRepoForStudents/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image

# Load the image
image_path = '/content/ladybug.png'  # replace with the path to your image
image = Image.open(image_path)

# Display the image
plt.imshow(image)
plt.axis('off')  # turn off the axis
plt.show()

In [ ]:
# Convert image to NumPy array
image_array = np.array(image)

# Print pixel values
print(image_array)

# Print shape of the image array (height, width, channels)
print("Shape of the image array:", image_array.shape)


In [1]:
import numpy as np

a1 = np.array([1, 2, 3])

a1.ndim, a1.shape, type(a1), a1.dtype, a1.size

(1, (3,), numpy.ndarray, dtype('int64'), 3)

In [2]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])

a2.ndim, a2.shape, type(a2), a2.dtype, a2.size

(2, (2, 3), numpy.ndarray, dtype('int64'), 6)

In [3]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],

               [[1, 3, 5],
                [3, 4, 2]]])

a3.ndim, a3.shape, type(a3), a3.dtype, a3.size

(3, (2, 2, 3), numpy.ndarray, dtype('int64'), 12)

In [4]:
np.random.seed(1)
random_arr = np.random.randint(1, 10, size = (2, 5, 5))
random_arr

array([[[6, 9, 6, 1, 1],
        [2, 8, 7, 3, 5],
        [6, 3, 5, 3, 5],
        [8, 8, 2, 8, 1],
        [7, 8, 7, 2, 1]],

       [[2, 9, 9, 4, 9],
        [8, 4, 7, 6, 2],
        [4, 5, 9, 2, 5],
        [1, 4, 3, 1, 5],
        [3, 8, 8, 9, 7]]])

In [5]:
np.random.randn(100)

array([-0.26788808,  0.53035547, -0.69166075, -0.39675353, -0.6871727 ,
       -0.84520564, -0.67124613, -0.0126646 , -1.11731035,  0.2344157 ,
        1.65980218,  0.74204416, -0.19183555, -0.88762896, -0.74715829,
        1.6924546 ,  0.05080775, -0.63699565,  0.19091548,  2.10025514,
        0.12015895,  0.61720311,  0.30017032, -0.35224985, -1.1425182 ,
       -0.34934272, -0.20889423,  0.58662319,  0.83898341,  0.93110208,
        0.28558733,  0.88514116, -0.75439794,  1.25286816,  0.51292982,
       -0.29809284,  0.48851815, -0.07557171,  1.13162939,  1.51981682,
        2.18557541, -1.39649634, -1.44411381, -0.50446586,  0.16003707,
        0.87616892,  0.31563495, -2.02220122, -0.30620401,  0.82797464,
        0.23009474,  0.76201118, -0.22232814, -0.20075807,  0.18656139,
        0.41005165,  0.19829972,  0.11900865, -0.67066229,  0.37756379,
        0.12182127,  1.12948391,  1.19891788,  0.18515642, -0.37528495,
       -0.63873041,  0.42349435,  0.07734007, -0.34385368,  0.04

In [21]:
np.random.seed(1)
random_arr = np.random.randint(1, 10, size = (2, 5, 5))
random_arr

array([[[6, 9, 6, 1, 1],
        [2, 8, 7, 3, 5],
        [6, 3, 5, 3, 5],
        [8, 8, 2, 8, 1],
        [7, 8, 7, 2, 1]],

       [[2, 9, 9, 4, 9],
        [8, 4, 7, 6, 2],
        [4, 5, 9, 2, 5],
        [1, 4, 3, 1, 5],
        [3, 8, 8, 9, 7]]])

In [23]:
random_arr[:, 3:, 3]

array([[8, 2],
       [1, 9]])

In [50]:
import time

start = time.time()
arr = np.random.randint(1, 10, size = (1_000_0000))
result = arr ** 10

end = time.time()

end - start

0.2817072868347168

In [51]:
start = time.time()

result = []
for i in range(1_000_0000):
    result.append(i ** 10)

end = time.time()

end - start

6.701652765274048

In [52]:
6.701652765274048 / 0.2817072868347168

23.78941929608672

In [40]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [43]:
a2, a2.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [44]:
a1, a1.shape

(array([1, 2, 3]), (3,))

In [45]:
a2.shape, a3.shape

((2, 3), (2, 2, 3))

In [46]:
a3 * a2

array([[[ 1,  4,  9],
        [16, 25, 36]],

       [[ 1,  6, 15],
        [12, 20, 12]]])

In [48]:
random_arr.shape

(2, 5, 5)

In [49]:
np.array([1, 2, 3]) * np.array([2, 2, 2])

array([2, 4, 6])

In [54]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [55]:
a2.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [56]:
a2.shape, a2.T.shape

((2, 3), (3, 2))

In [57]:
a2.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [61]:
random_arr.shape

(2, 5, 5)

In [62]:
random_arr.size

50

In [68]:
a2.shape, a2.T.shape

((2, 3), (3, 2))

In [69]:
a2 @ a2.T

array([[14, 32],
       [32, 77]])

In [70]:
np.dot(a2, a2.T)

array([[14, 32],
       [32, 77]])

In [71]:
np.matmul(a2, a2.T)

array([[14, 32],
       [32, 77]])

In [77]:
np.sum(a3)

39

In [78]:
sum(a3)

array([[2, 5, 8],
       [7, 9, 8]])

In [84]:
np.zeros(shape = (3, 5, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [85]:
np.ones(shape = (3, 3, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [88]:
a2.var(), a2.std()

(2.9166666666666665, 1.707825127659933)